export interface QuizQuestion {
  q: string;
  options: string[];
  correct: number; // index
  explanation: string;
}

export const QUIZ_DATA: Record<string, QuizQuestion[]> = {
  etf: [
    { q: "¿Qué es un ETF?", options: ["Un fondo que cotiza en bolsa como una acción", "Un bono del gobierno", "Una cuenta de ahorros", "Un préstamo bancario"], correct: 0, explanation: "Un ETF (Exchange Traded Fund) es un fondo de inversión que cotiza en bolsa igual que una acción." },
    { q: "¿Cuál es una ventaja clave de los ETFs?", options: ["Garantizan ganancias", "Permiten diversificación a bajo costo", "Son solo para inversores institucionales", "No tienen riesgo de mercado"], correct: 1, explanation: "Los ETFs permiten invertir en muchas empresas o activos a la vez con una sola compra y comisiones muy bajas." },
    { q: "¿Qué diferencia hay entre un ETF y un fondo mutuo?", options: ["Los ETFs se compran directamente al fondo", "Los ETFs cotizan en bolsa durante el día; los fondos mutuos se valúan al cierre", "Los fondos mutuos tienen menores costos siempre", "No hay diferencia"], correct: 1, explanation: "Los ETFs cotizan como acciones en tiempo real; los fondos mutuos se valúan una vez al día al precio de cierre (NAV)." },
  ],
  accion: [
    { q: "¿Qué representa una acción?", options: ["Una deuda de la empresa con el inversor", "Una fracción de la propiedad de una empresa", "Un depósito a plazo fijo", "Un contrato de seguro"], correct: 1, explanation: "Al comprar una acción eres accionista y propietario de una pequeña fracción de la empresa." },
    { q: "¿Qué mueve principalmente el precio de una acción?", options: ["El número de empleados", "Las expectativas de ganancias futuras y la oferta/demanda", "El color del logo de la empresa", "La edad de la empresa"], correct: 1, explanation: "El precio refleja principalmente las expectativas del mercado sobre las ganancias futuras, más la oferta y demanda en tiempo real." },
    { q: "¿Qué es una acción preferente?", options: ["Una acción con derecho a voto doble", "Una acción que paga dividendo fijo y tiene prioridad en liquidación", "Una acción emitida por el gobierno", "Una acción con precio garantizado"], correct: 1, explanation: "Las acciones preferentes tienen dividendo fijo y prioridad sobre las ordinarias si la empresa quiebra, pero generalmente no tienen voto." },
  ],
  dividendo: [
    { q: "¿Qué es un dividendo?", options: ["El precio de compra de una acción", "Una distribución de ganancias de la empresa a sus accionistas", "Un préstamo de la empresa", "El valor en libros de la acción"], correct: 1, explanation: "Los dividendos son pagos que la empresa hace a sus accionistas como distribución de sus ganancias." },
    { q: "¿Qué es el dividend yield?", options: ["El precio histórico más alto", "El dividendo anual dividido entre el precio de la acción", "La cantidad de acciones en circulación", "El dividendo del año anterior"], correct: 1, explanation: "Dividend Yield = Dividendo anual / Precio de la acción. Indica el rendimiento por dividendo como porcentaje." },
    { q: "¿Qué significa 'ex-dividend date'?", options: ["La fecha límite para recibir el dividendo declarado", "La fecha en que la empresa cancela el dividendo", "La fecha de pago del dividendo", "La fecha de la junta de accionistas"], correct: 0, explanation: "Para recibir el dividendo debes ser accionista ANTES de la ex-dividend date. Quien compre en esa fecha o después no lo recibe." },
  ],
  interes_c: [
    { q: "¿En qué se basa el interés compuesto?", options: ["En ganar interés solo sobre el capital inicial", "En ganar interés sobre el capital más los intereses acumulados", "En dividir el dinero entre periodos", "En deducir impuestos automáticamente"], correct: 1, explanation: "El interés compuesto se calcula sobre el capital original MÁS los intereses ya ganados — por eso crece exponencialmente." },
    { q: "¿Cuál es la Regla del 72?", options: ["El número máximo de acciones que se deben tener", "Divides 72 entre la tasa de interés para saber en cuántos años se duplica el capital", "El porcentaje mínimo de bonos en un portafolio", "El tiempo en días para liquidar una operación"], correct: 1, explanation: "72 / tasa de interés = años para duplicar el dinero. Con 8% anual: 72/8 = 9 años para duplicar." },
    { q: "¿Por qué el tiempo es tan importante en el interés compuesto?", options: ["Porque los precios suben con la inflación", "Porque el crecimiento se acelera exponencialmente con más tiempo", "Porque los impuestos son menores a largo plazo", "Porque las tasas de interés siempre suben"], correct: 1, explanation: "El compuesto es exponencial: los primeros años crecen poco, pero con el tiempo cada período aporta más que todos los anteriores juntos." },
  ],
  pe_ratio: [
    { q: "¿Cómo se calcula el P/E ratio?", options: ["Precio ÷ Dividendo", "Precio de la acción ÷ Ganancias por acción (EPS)", "Ganancias ÷ Capital total", "Ventas ÷ Precio"], correct: 1, explanation: "P/E = Precio de la acción / EPS (Earnings Per Share). Indica cuánto pagas por cada dólar de ganancia." },
    { q: "Un P/E de 30 vs uno de 15 (misma industria), ¿qué podría indicar?", options: ["El de 30 es siempre mejor", "El mercado espera mayor crecimiento de la empresa con P/E 30", "El de 30 tiene más dividendos", "El de 15 tiene más deuda"], correct: 1, explanation: "Un P/E más alto puede indicar que el mercado espera mayor crecimiento futuro — pero también puede significar sobrevaluación." },
    { q: "¿Qué limitación importante tiene el P/E ratio?", options: ["Solo funciona para empresas grandes", "No sirve para empresas con pérdidas y puede distorsionarse por ítems no recurrentes", "Solo aplica en mercados emergentes", "No toma en cuenta el precio de la acción"], correct: 1, explanation: "Si la empresa tiene pérdidas el P/E no aplica. Además, ganancias extraordinarias o escribanías pueden distorsionarlo." },
  ],
  dca: [
    { q: "¿En qué consiste el Dollar Cost Averaging (DCA)?", options: ["Invertir todo el capital de una sola vez cuando el mercado está bajo", "Invertir una cantidad fija a intervalos regulares sin importar el precio", "Mover el dinero entre acciones según el precio diario", "Comprar solo cuando el precio baja un 10%"], correct: 1, explanation: "Con DCA inviertes la misma cantidad cada semana/mes, comprando más acciones cuando el precio está bajo y menos cuando está alto." },
    { q: "¿Cuál es el principal beneficio del DCA?", options: ["Garantiza rendimientos positivos", "Reduce el impacto del timing del mercado y el estrés de decisión", "Maximiza ganancias en mercados alcistas", "Elimina el riesgo de mercado"], correct: 1, explanation: "DCA no requiere predecir el mercado. Automáticamente comprás a un precio promedio, reduciendo el riesgo de invertir todo en el pico." },
    { q: "¿Cuándo podría ser mejor un 'lump sum' (invertir todo de una vez) vs DCA?", options: ["Nunca, DCA siempre es mejor", "Cuando el mercado claramente va a subir, el lump sum históricamente supera al DCA", "Cuando los tipos de interés están altos", "Cuando la inflación es negativa"], correct: 1, explanation: "Estadísticamente, invertir todo de una vez supera al DCA ~2/3 del tiempo porque los mercados suben la mayoría de los días." },
  ],
  diversif: [
    { q: "¿Por qué funciona la diversificación?", options: ["Porque garantiza que siempre habrá activos que suban", "Porque activos con baja correlación reducen el riesgo total sin sacrificar tanto rendimiento", "Porque los ETFs son más seguros que las acciones", "Porque el gobierno protege portafolios diversificados"], correct: 1, explanation: "Al combinar activos que no se mueven igual, cuando uno baja otro puede subir o moverse menos, reduciendo la volatilidad total." },
    { q: "¿Cuántas acciones se necesitan aproximadamente para una diversificación básica?", options: ["1-3", "2-5", "15-20", "500+"], correct: 2, explanation: "Con ~15-20 acciones bien elegidas de diferentes sectores se captura la mayor parte del beneficio de la diversificación." },
    { q: "¿Qué es la 'sobre-diversificación'?", options: ["Tener más de 5 acciones", "Tener demasiados activos hasta que el portafolio se comporta como el índice pero con más costos", "Invertir en más de dos países", "Tener bonos y acciones al mismo tiempo"], correct: 1, explanation: "Con demasiados activos el portafolio replica al índice pero con mayores comisiones y sin posibilidad de superarlo." },
  ],
  bull_bear: [
    { q: "¿Cómo se define técnicamente un mercado bajista (bear market)?", options: ["Cuando la bolsa baja un 5% en un día", "Una caída del 20% o más desde el máximo reciente sostenida en el tiempo", "Cuando el PIB crece menos de 2%", "Cuando los bonos rinden más que las acciones"], correct: 1, explanation: "Un bear market es una caída sostenida de 20%+ desde el último máximo. Una corrección es una caída de 10-20%." },
    { q: "¿Cuánto suelen durar los mercados alcistas (bull markets) históricamente vs los bajistas?", options: ["Son iguales en duración", "Los bull son más cortos que los bear", "Los bull duran mucho más que los bear", "Los bear duran exactamente 1 año"], correct: 2, explanation: "Históricamente los bull markets duran años (promedio ~9 años) mientras los bear markets son más cortos (promedio ~1-2 años)." },
    { q: "¿Cuál es el mejor enfoque para el inversor a largo plazo durante un bear market?", options: ["Vender todo para evitar pérdidas", "Mantener o comprar más, sabiendo que los mercados históricamente se recuperan", "Mover todo a criptomonedas", "Esperar a que el mercado caiga otro 50%"], correct: 1, explanation: "Los inversores exitosos como Buffett ven los bear markets como oportunidades de compra. El pánico y vender en mínimos destruye riqueza." },
  ],
  earnings: [
    { q: "¿Qué es el EPS (Earnings Per Share)?", options: ["El precio de la acción dividido entre sus ventas", "La ganancia neta de la empresa dividida entre el número de acciones en circulación", "El dividendo por acción pagado", "El ingreso bruto de la empresa"], correct: 1, explanation: "EPS = Ganancia neta / Acciones en circulación. Es la medida más básica de cuánto gana la empresa por cada acción." },
    { q: "¿Qué significa que una empresa 'beat' el consenso de ganancias?", options: ["Que sus acciones subieron ese día", "Que su EPS real superó las estimaciones promedio de los analistas", "Que declaró un dividendo mayor al esperado", "Que vendió más productos que el trimestre anterior"], correct: 1, explanation: "'Beat earnings' significa que el EPS reportado fue mayor al estimado por los analistas de Wall Street." },
    { q: "¿Por qué puede bajar una acción aunque la empresa 'beat' sus estimaciones?", options: ["Eso nunca ocurre", "Si el guidance (perspectivas futuras) fue decepcionante o ya estaba en precio", "Porque los inversores no leen los reportes", "Porque el CEO no da declaraciones"], correct: 1, explanation: "Si el mercado ya anticipaba el beat o si la empresa da guidance decepcionante para el próximo trimestre, la acción puede caer." },
  ],
  moat: [
    { q: "¿Qué es un 'moat' económico según Warren Buffett?", options: ["El precio justo de una acción", "Una ventaja competitiva duradera que protege los beneficios de la empresa de la competencia", "La cuota de mercado de la empresa", "La deuda a largo plazo de la empresa"], correct: 1, explanation: "El 'moat' (foso) es la ventaja que hace difícil que los competidores le quiten clientes o rentabilidad a una empresa." },
    { q: "¿Cuál de estos es un ejemplo de moat por 'costo de cambio'?", options: ["Tener la marca más reconocida", "Que los clientes pierdan mucho si cambian a la competencia (ej: software ERP en una empresa)", "Ser la opción más barata del mercado", "Tener las mejores instalaciones físicas"], correct: 1, explanation: "Si cambiar de proveedor cuesta tiempo, dinero y esfuerzo (como cambiar el sistema ERP de una empresa), eso es un moat de switching costs." },
    { q: "¿Qué tipo de moat tiene Coca-Cola?", options: ["Costos de cambio", "Ventaja en costos por escala de producción", "Marca reconocida mundialmente (intangible) y red de distribución", "Patentes de tecnología"], correct: 2, explanation: "Coca-Cola tiene un moat de marca (intangible assets) y una red de distribución global que es casi imposible de replicar." },
  ],
  recesion: [
    { q: "¿Cuál es la definición técnica de recesión?", options: ["Una caída de bolsa mayor al 20%", "Dos trimestres consecutivos de contracción del PIB", "Desempleo superior al 10%", "Caída de exportaciones por 6 meses"], correct: 1, explanation: "Técnicamente, recesión = dos trimestres consecutivos de crecimiento negativo del PIB, aunque la definición oficial puede variar." },
    { q: "¿Qué sectores suelen resistir mejor en una recesión?", options: ["Tecnología y lujo", "Consumo básico, salud y servicios públicos (utilities)", "Automotriz y construcción", "Viajes y entretenimiento"], correct: 1, explanation: "Los sectores defensivos (alimentos, medicamentos, electricidad) mantienen demanda en recesión porque son necesidades básicas." },
    { q: "¿Qué indicador suele anticipar recesiones antes de que ocurran?", options: ["El precio del petróleo", "La curva de rendimientos invertida (yield curve inversion)", "El número de IPOs", "El precio del oro"], correct: 1, explanation: "Cuando los bonos a corto plazo rinden más que los de largo plazo (curva invertida), históricamente ha precedido recesiones." },
  ],
  value_inv: [
    { q: "¿Cuál es el principio central del Value Investing?", options: ["Comprar acciones que ya subieron mucho", "Comprar empresas por debajo de su valor intrínseco esperando que el mercado corrija el precio", "Invertir solo en índices", "Comprar y vender rápidamente en tendencias"], correct: 1, explanation: "Value investing busca empresas cuyo precio de mercado es menor a su valor real (intrínseco), comprando con 'margen de seguridad'." },
    { q: "¿Qué es el 'margen de seguridad' de Benjamin Graham?", options: ["El seguro de inversión gubernamental", "La diferencia entre el valor intrínseco estimado y el precio de compra, para protegerse de errores de cálculo", "El porcentaje máximo de pérdida aceptable", "El dividendo anual como porcentaje del precio"], correct: 1, explanation: "Si estimas que una empresa vale $100 y compras a $60, tu margen de seguridad es del 40%, protegiendo contra errores en tu análisis." },
    { q: "¿Por qué es difícil el value investing en la práctica?", options: ["Porque no existen empresas baratas", "Porque requiere paciencia para esperar que el mercado reconozca el valor, lo cual puede tomar años", "Porque los brokers no permiten comprar acciones baratas", "Porque el gobierno grava las ganancias de value investors más"], correct: 1, explanation: "Una acción 'barata' puede seguir bajando ('value trap'). Requiere convicción, análisis profundo y años de paciencia." },
  ],
  tasas: [
    { q: "Cuando la Fed sube las tasas de interés, ¿qué suele ocurrir con los precios de los bonos?", options: ["Suben", "No cambian", "Bajan", "Se vuelven impredecibles"], correct: 2, explanation: "Tasas de interés y precios de bonos tienen relación inversa: si las tasas suben, los bonos existentes valen menos porque pagan cupones inferiores." },
    { q: "¿Qué tipo de acciones suelen sufrir más cuando suben las tasas?", options: ["Empresas de consumo básico", "Empresas growth (alta valuación, flujos futuros lejanos)", "Empresas bancarias", "Empresas con mucho efectivo"], correct: 1, explanation: "Las empresas growth se valúan por flujos de caja futuros descontados. Tasas más altas = mayor tasa de descuento = menor valor presente." },
    { q: "¿Por qué los bancos se benefician de tasas más altas?", options: ["Porque prestan más dinero", "Porque el spread entre tasas de depósito y préstamo generalmente se amplía", "Porque sus clientes ahorran más", "Porque el gobierno les subsidia"], correct: 1, explanation: "Los bancos ganan la diferencia entre lo que pagan por depósitos y lo que cobran por préstamos. Con tasas altas este spread suele aumentar." },
  ],
  roe: [
    { q: "¿Cómo se calcula el ROE?", options: ["Precio / Ganancias", "Ganancia neta / Patrimonio neto × 100", "Ventas / Total activos", "EBITDA / Deuda total"], correct: 1, explanation: "ROE = Ganancia neta / Equity (patrimonio de los accionistas) × 100. Mide qué tan eficientemente la empresa usa el capital propio." },
    { q: "¿Qué significa un ROE del 20% vs uno del 8% (misma industria)?", options: ["La empresa con 20% es más pequeña", "La empresa con 20% genera más ganancia por cada dólar de capital propio invertido", "La empresa con 8% tiene más deuda", "No hay diferencia relevante"], correct: 1, explanation: "Un ROE más alto indica mayor eficiencia. Buffett busca empresas con ROE consistentemente superior al 15%." },
    { q: "¿Por qué un ROE muy alto puede ser engañoso?", options: ["Porque el gobierno lo manipula", "Porque puede estar inflado por exceso de deuda (apalancamiento financiero)", "Porque solo aplica en ciertos sectores", "Porque siempre significa más dividendos"], correct: 1, explanation: "Una empresa muy endeudada puede mostrar ROE alto porque tiene poco equity. La fórmula DuPont separa qué parte viene del apalancamiento." },
  ],
  nvidia: [
    { q: "¿Cuál es el principal negocio de NVIDIA actualmente?", options: ["Fabricación de teléfonos móviles", "GPUs para centros de datos e inteligencia artificial", "Software de productividad empresarial", "Procesadores para computadoras personales"], correct: 1, explanation: "NVIDIA lidera el mercado de GPUs para IA, con sus chips H100 y A100 siendo la infraestructura clave para entrenar modelos de IA." },
    { q: "¿Qué es el 'moat' de NVIDIA?", options: ["Sus tiendas minoristas", "El ecosistema CUDA y su posición dominante en GPUs para IA que hace difícil cambiar a la competencia", "Ser la empresa más antigua del sector", "Tener el mayor número de empleados"], correct: 1, explanation: "CUDA (su plataforma de software para GPUs) es el moat real: los desarrolladores de IA llevan años programando para CUDA y cambiar es costoso." },
    { q: "¿Cuál es el principal riesgo de invertir en NVIDIA?", options: ["Que no tenga suficientes clientes", "La ciclicidad del sector chips, competencia de AMD/Intel y posible regulación en exportaciones de chips a China", "Que no pague dividendos", "Que sea una empresa demasiado pequeña"], correct: 1, explanation: "Los semiconductores son cíclicos y NVIDIA depende en parte de China. Además AMD y los propios clientes (Google, Amazon) desarrollan chips propios." },
  ],
  apple: [
    { q: "¿Qué segmento es el más grande en ingresos de Apple actualmente?", options: ["Mac", "iPhone", "Servicios (App Store, iCloud, Apple TV+)", "iPad"], correct: 1, explanation: "iPhone sigue siendo el mayor generador de ingresos, aunque los Servicios crecen más rápido y tienen márgenes mucho mayores." },
    { q: "¿En qué consiste el 'moat' del ecosistema de Apple?", options: ["En tener el hardware más barato", "En los altos costos de cambio: si usas iPhone, Mac, iPad y AirPods todo integrado, salirse es muy costoso", "En ser la empresa con más patentes", "En sus canales de distribución exclusivos"], correct: 1, explanation: "El ecosistema Apple crea 'lock-in': cada producto que usas hace más costoso cambiarte a otra plataforma." },
    { q: "¿Qué es el programa de recompra de acciones (buyback) de Apple y por qué importa?", options: ["Apple emite nuevas acciones para financiarse", "Apple compra sus propias acciones reduciendo el número en circulación, lo que aumenta el EPS para los accionistas restantes", "Apple regala acciones a empleados", "Apple fusiona acciones para subir el precio unitario"], correct: 1, explanation: "Con sus buybacks masivos, Apple ha recomprado ~40% de sus acciones en 10 años, aumentando el valor por acción de los que permanecen." },
  ],
  sesgo_c: [
    { q: "¿En qué consiste el sesgo de confirmación en inversiones?", options: ["En creer que lo que subió ayer seguirá subiendo", "En buscar y recordar solo información que confirma nuestra tesis, ignorando evidencia contraria", "En copiar las inversiones de otros", "En tener miedo a perder dinero"], correct: 1, explanation: "Cuando estamos convencidos de una inversión, tendemos a ignorar noticias negativas y a sobreponderar las positivas." },
    { q: "¿Cuál de estos es un ejemplo de sesgo de confirmación?", options: ["Vender cuando la acción baja", "Leer solo análisis positivos de una empresa en la que ya invertiste y descartar críticas", "Diversificar el portafolio", "Usar stop-loss"], correct: 1, explanation: "Si compraste TSLA y solo lees los toros de Tesla ignorando los análisis bajistas, estás sufriendo sesgo de confirmación." },
    { q: "¿Cómo contrarrestar el sesgo de confirmación?", options: ["Confiar más en tu instinto", "Buscar activamente tesis contrarias, leer análisis bajistas y usar el pensamiento de 'abogado del diablo'", "Invertir solo en índices", "Consultar solo a un experto de confianza"], correct: 1, explanation: "El antídoto es el pensamiento crítico activo: busca razones por las que tu tesis PODRÍA estar equivocada antes de invertir." },
  ],
  aversion: [
    { q: "Según Kahneman y Tversky, ¿cuánto duele una pérdida vs una ganancia del mismo monto?", options: ["Igual", "Las pérdidas duelen aproximadamente el doble que lo que alegra una ganancia equivalente", "Las ganancias producen más emoción que las pérdidas", "Depende del monto total del portafolio"], correct: 1, explanation: "Perder $1,000 duele psicológicamente el doble que ganar $1,000 produce alegría. Esto distorsiona nuestras decisiones de inversión." },
    { q: "¿Cómo afecta la aversión a la pérdida a los inversores?", options: ["Los hace más disciplinados", "Los lleva a vender ganadores muy rápido y mantener perdedores demasiado tiempo (para 'no realizar la pérdida')", "Los hace más pacientes", "No tiene efecto si se tiene un asesor financiero"], correct: 1, explanation: "El 'disposition effect': vendemos los ganadores rápido (para asegurar la ganancia) y aguantamos perdedores esperando recuperar." },
    { q: "¿Cuál es la estrategia más efectiva para manejar la aversión a la pérdida?", options: ["Revisar el portafolio varias veces al día", "Definir reglas pre-establecidas (ej: no revisar más de 1 vez/semana) y automatizar las inversiones", "Invertir solo en lo que conoces bien", "Consultar a otros inversores constantemente"], correct: 1, explanation: "Revisar el portafolio frecuentemente activa la aversión a pérdidas con cada baja pequeña. Menos revisión = mejores decisiones." },
  ],
  fomo: [
    { q: "¿Qué es el FOMO en inversiones?", options: ["Un tipo de fondo de inversión", "El miedo a perderse una oportunidad que lleva a tomar decisiones impulsivas", "Una estrategia de trading", "Un indicador técnico"], correct: 1, explanation: "FOMO (Fear Of Missing Out) es la ansiedad de que otros están ganando con algo en lo que tú no estás, llevando a comprar en picos." },
    { q: "¿Cuál fue un ejemplo claro de FOMO masivo en mercados?", options: ["La caída de Lehman Brothers en 2008", "Bitcoin en 2021 y acciones de GameStop — mucha gente compró en máximos por FOMO y perdió significativamente", "La burbuja de las punto com en 1999", "Todos los anteriores son ejemplos de FOMO"], correct: 3, explanation: "El FOMO está detrás de la mayoría de las burbujas: los tres casos son ejemplos clásicos donde el miedo a perderse el rally llevó a comprar en picos." },
    { q: "¿Qué estrategia ayuda a evitar decisiones por FOMO?", options: ["Seguir las tendencias en redes sociales", "Tener una política de inversión personal escrita con criterios claros antes de cualquier compra", "Invertir solo cuando muchos conocidos lo hacen", "Revisar precios en tiempo real constantemente"], correct: 1, explanation: "Una Investment Policy Statement (IPS) personal con tus criterios te protege de impulsos: si no cumple los criterios, no compras." },
  ],
};
