import { describe, it, expect } from "vitest";
import { projectDriverBasedDcf, UnstableGordonGrowthError } from "./driverBasedDcf";

// Expected values below were generated by running the real Python engine
// (backend/app/services/valuation/dcf_engine.py::project_driver_based_dcf)
// with the identical inputs — this test's job is to prove the TS port stays
// numerically identical to the backend, not to re-derive the math.
describe("projectDriverBasedDcf — parity with the Python engine", () => {
  it("matches Gordon-growth mode (no plateau) exactly", () => {
    const r = projectDriverBasedDcf({
      revenue0: 1000.0,
      revenueGrowth1: 0.15,
      terminalGrowth: 0.03,
      operatingMarginAnchorPct: 0.2,
      terminalOperatingMarginPct: 0.22,
      taxRate: 0.21,
      reinvestmentRateAnchorPct: 0.3,
      terminalRoicPct: 0.15,
      discountRate: 0.09,
      netCash: 500.0,
      sharesOut: 100.0,
    });

    expect(r.valuePerShare).toBe(40.82);
    expect(r.enterpriseValue).toBe(3582.0);
    expect(r.pvOfFcfSum).toBe(1334.0);
    expect(r.terminalValue).toBe(5322.0);
    expect(r.yearly[0].revenue).toBe(1138.0);
    expect(r.yearly[9].fcf).toBe(310.0);
    expect(r.assumptions.terminalValueMethod).toBe("gordon");
  });

  it("matches exit-multiple mode with a 3-year plateau exactly", () => {
    const r = projectDriverBasedDcf({
      revenue0: 2000.0,
      revenueGrowth1: 0.25,
      terminalGrowth: 0.025,
      operatingMarginAnchorPct: 0.18,
      terminalOperatingMarginPct: 0.24,
      taxRate: 0.23,
      reinvestmentRateAnchorPct: 0.35,
      terminalRoicPct: 0.18,
      discountRate: 0.095,
      netCash: -200.0,
      sharesOut: 250.0,
      highGrowthYears: 3,
      exitMultiple: 4.0,
      exitMetric: "ev_sales",
    });

    expect(r.valuePerShare).toBe(72.06);
    expect(r.enterpriseValue).toBe(18214.0);
    expect(r.pvOfFcfSum).toBe(4312.0);
    expect(r.terminalValue).toBe(34452.0);
    expect(r.assumptions.gordonSanityCheckRatio).toBe(1.72);
    expect(r.yearly[3].revenueGrowthPct).toBe(21.79);
    expect(r.yearly[9].revenue).toBe(8613.0);
    expect(r.assumptions.terminalValueMethod).toBe("exit_multiple");
  });

  it("throws UnstableGordonGrowthError in Gordon-only mode when the WACC/terminal-growth spread is too thin", () => {
    expect(() =>
      projectDriverBasedDcf({
        revenue0: 1000,
        revenueGrowth1: 0.1,
        terminalGrowth: 0.05,
        operatingMarginAnchorPct: 0.2,
        terminalOperatingMarginPct: 0.2,
        taxRate: 0.21,
        reinvestmentRateAnchorPct: 0.3,
        terminalRoicPct: 0.15,
        discountRate: 0.052,
      })
    ).toThrow(UnstableGordonGrowthError);
  });

  it("does not throw in exit-multiple mode under the same thin spread — the sanity check just becomes unavailable", () => {
    const r = projectDriverBasedDcf({
      revenue0: 1000,
      revenueGrowth1: 0.1,
      terminalGrowth: 0.05,
      operatingMarginAnchorPct: 0.2,
      terminalOperatingMarginPct: 0.2,
      taxRate: 0.21,
      reinvestmentRateAnchorPct: 0.3,
      terminalRoicPct: 0.15,
      discountRate: 0.052,
      exitMultiple: 10,
      exitMetric: "ev_ebit",
    });
    expect(r.assumptions.gordonTerminalValue).toBeNull();
    expect(r.assumptions.gordonSanityCheckRatio).toBeNull();
    expect(r.enterpriseValue).toBeGreaterThan(0);
  });

  it("returns null equityValue/valuePerShare without netCash/sharesOut", () => {
    const r = projectDriverBasedDcf({
      revenue0: 1000,
      revenueGrowth1: 0.1,
      terminalGrowth: 0.03,
      operatingMarginAnchorPct: 0.2,
      terminalOperatingMarginPct: 0.2,
      taxRate: 0.21,
      reinvestmentRateAnchorPct: 0.3,
      terminalRoicPct: 0.15,
      discountRate: 0.09,
    });
    expect(r.equityValue).toBeNull();
    expect(r.valuePerShare).toBeNull();
  });

  it("rejects a plateau covering the whole projection", () => {
    expect(() =>
      projectDriverBasedDcf({
        revenue0: 1000,
        revenueGrowth1: 0.1,
        terminalGrowth: 0.03,
        operatingMarginAnchorPct: 0.2,
        terminalOperatingMarginPct: 0.2,
        taxRate: 0.21,
        reinvestmentRateAnchorPct: 0.3,
        terminalRoicPct: 0.15,
        discountRate: 0.09,
        highGrowthYears: 10,
      })
    ).toThrow(/high_growth_years/);
  });
});
